    - name: Set up Drupal
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        vendor/bin/drush site:install standard \
          --db-url=mysql://root:root@$DB_HOST:$DB_PORT/drupal \
          --account-name=admin \
          --account-pass=admin \
          --yes
        vendor/bin/drush config:set system.site uuid $(vendor/bin/drush config:get system.site:uuid --format=string) --yes
        vendor/bin/drush config:import --yes
        vendor/bin/drush cache:rebuild
